# Generated by Django 3.1.1 on 2021-12-08 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2021-08-12'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='offer_type',
            field=models.CharField(choices=[('Rent', 'Rent'), ('Sale', 'Sale'), ('', 'please choose')], default='', max_length=25, verbose_name='OFFER_TYPE'),
        ),
    ]
